# Generated by Django 5.2.8 on 2025-11-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportePrecalculado',
            fields=[
                ('n_features', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('resultados_json', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reportes_precalculados_features',
            },
        ),
    ]
